[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# Health check removed - not needed for demo project

[[crons]]
schedule = "0 2 * * *"
command = "dotnet ASPNETCRUD.API.dll --reset-database" 