[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 90
healthcheckInterval = 15
healthcheckRetries = 5

[[crons]]
schedule = "0 2 * * *"
command = "dotnet ASPNETCRUD.API.dll --reset-database" 