[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "dotnet ASPNETCRUD.API.dll"
healthcheckPath = "/health"
healthcheckTimeout = 10

[env]
PORT = "8000"
ASPNETCORE_URLS = "http://+:8000"
ASPNETCORE_ENVIRONMENT = "Production"

# TEMPORARILY DISABLED - Run at 2 AM UTC every day
# [[crons]]
# schedule = "0 2 * * *"
# command = "dotnet ASPNETCRUD.API.dll --reset-database" 