[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
startCommand = "python simple_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
ASPNETCORE_URLS = "http://+:8000"
ASPNETCORE_ENVIRONMENT = "Production"

# TEMPORARILY DISABLED - Run at 2 AM UTC every day
# [[crons]]
# schedule = "0 2 * * *"
# command = "dotnet ASPNETCRUD.API.dll --reset-database" 