[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# Health check removed - not needed for demo project

# TEMPORARILY DISABLED - Run at 2 AM UTC every day
# [[crons]]
# schedule = "0 2 * * *"
# command = "dotnet ASPNETCRUD.API.dll --reset-database" 