[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
ASPNETCORE_URLS = "http://+:8080"
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_DETAILEDERRORS = "true"
DOTNET_PRINT_TELEMETRY_MESSAGE = "false"
SwaggerAuth__Username = "portfolio"
SwaggerAuth__Password = "demo2024"
DemoSettings__ApiKey = "demo-reset-key-2024" 