[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
ASPNETCORE_URLS = "http://+:8000"
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_DETAILEDERRORS = "true"
DOTNET_PRINT_TELEMETRY_MESSAGE = "false"

# TEMPORARILY DISABLED - Run at 2 AM UTC every day
# [[crons]]
# schedule = "0 2 * * *"
# command = "dotnet ASPNETCRUD.API.dll --reset-database" 